### ISSUE TITLE
Wrong / confusing error msg when file is not found (KeyError: '.ods')

### ISSUE THREAD

**Issue by academay** [pyexcel/pyexcel-io#100]
When opening a non existing file, an irrelevant msg is given. It's minor issue.

```
>>> from pyexcel_ods3 import get_data
>>> f = 'file-not-exist.ods'
>>> data = get_data(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_ods3/__init__.py", line 50, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/io.py", line 86, in get_data
    data, _ = _get_data(
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/io.py", line 105, in _get_data
    return load_data(**keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/io.py", line 191, in load_data
    reader.open(file_name, **keywords)
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_io/reader.py", line 47, in open
    self.reader = self.reader_class(
  File "/home/dy/.local/lib/python3.8/site-packages/pyexcel_ods3/odsr.py", line 64, in __init__
    self.ods_book = ezodf.opendoc(file_alike_object)
  File "/home/dy/.local/lib/python3.8/site-packages/ezodf/document.py", line 54, in opendoc
    mime_type = __detect_mime_type(fm)
  File "/home/dy/.local/lib/python3.8/site-packages/ezodf/document.py", line 69, in __detect_mime_type
    mime_type = MIMETYPES[ext]
KeyError: '.ods'
```

I guess this error can be caught or proper exception thrown when the input is assumed to be a file (?).

**Comment by chfw** [comment]
yes and no.

yes, as a dummy user facing application, it is good to catch it and throw a friendlier message.

no, for developer facing library, it is a bad idea to swallow an exception and throw another one, because it hides what went wrong and it cost the developer time to find out why.
