### ISSUE TITLE
Latest version (0.5.13) does not play well with pyexcel-xlsx (0.5.6)

### ISSUE THREAD

**Issue by charles-cooper** [pyexcel/pyexcel-io#66]
I can't post the data but here's a traceback
```
Traceback (most recent call last):
  File "scripts/munge_data.py", line 216, in <module>
    res = munge(args.filepath)
  File "scripts/munge_data.py", line 160, in munge_file
    records = excel.get_data(afile=res, file_type='xlsx')\
  File "/usr/local/lib/python3.6/dist-packages/pyexcel_io/io.py", line 71, in get_data
    afile, file_type=file_type, streaming=False, **keywords
  File "/usr/local/lib/python3.6/dist-packages/pyexcel_io/io.py", line 89, in _get_data
    return load_data(**keywords)
  File "/usr/local/lib/python3.6/dist-packages/pyexcel_io/io.py", line 202, in load_data
    result[key] = list(result[key])
  File "/usr/local/lib/python3.6/dist-packages/pyexcel_io/sheet.py", line 77, in to_array
    self.column_iterator(row)
  File "/usr/local/lib/python3.6/dist-packages/pyexcel_xlsx/xlsxr.py", line 101, in column_iterator
    value = cell.value
AttributeError: 'MergedCell' object has no attribute 'value'
```
(python version is 3.6.7)

**Comment by chfw** [comment]
https://travis-ci.org/pyexcel/pyexcel-xlsx/jobs/358641126 reproduced. Will fix it.

**Comment by chfw** [comment]
please pin openpyxl < 2.6.0

**Comment by chfw** [comment]
it turns out that 2.6.0 had been badly wrong. Any version after 2.6.0 seemed OK. pyexcel-xlsx 0.5.8 has relax the restriction.
